#ifndef INLINEBIN_H
#define INLINEBIN_H

enum inlinebin {
	INLINEBIN_NONE,
	SHADER_BASEMAP_SPHERICAL_VERTEX,
	SHADER_BASEMAP_SPHERICAL_FRAGMENT,
	SHADER_BKGD_VERTEX,
	SHADER_BKGD_FRAGMENT,
	SHADER_FRUSTUM_VERTEX,
	SHADER_FRUSTUM_FRAGMENT,
	SHADER_SOLID_VERTEX,
	SHADER_SOLID_FRAGMENT,
	SHADER_TILE2D_VERTEX,
	SHADER_TILE2D_FRAGMENT,
	TEXTURE_BACKGROUND,
	TEXTURE_BASEMAP,
	TEXTURE_COPYRIGHT,
	TEXTURE_CURSOR,
};

void inlinebin_get (enum inlinebin member, const char **buf, size_t *len);

#endif	/* INLINEBIN_H */
