#pragma once

#include <stdint.h>
#include <stddef.h>

enum Inlinebin {
	INLINEBIN_NONE,
	SHADER_BASEMAP_VERTEX,
	SHADER_BASEMAP_FRAGMENT,
	SHADER_BKGD_VERTEX,
	SHADER_BKGD_FRAGMENT,
	SHADER_FRUSTUM_VERTEX,
	SHADER_FRUSTUM_FRAGMENT,
	SHADER_SOLID_VERTEX,
	SHADER_SOLID_FRAGMENT,
	SHADER_SPHERICAL_VERTEX,
	SHADER_SPHERICAL_FRAGMENT,
	SHADER_TILE2D_VERTEX,
	SHADER_TILE2D_FRAGMENT,
	SHADER_TILEPICKER_VERTEX,
	SHADER_TILEPICKER_FRAGMENT,
	TEXTURE_BACKGROUND,
	TEXTURE_COPYRIGHT,
	TEXTURE_CURSOR,
};

extern void inlinebin_get (enum Inlinebin member, const uint8_t **buf, size_t *len);
